### ISSUE TITLE
Exceptions in promise using algorithms

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/permissions#102]
In the "permission request algorithm", the spec says: 

>  May throw an exception if the request can fail exceptionally.

This is wrong - and seems to read like it's going to throw exceptionally when called. It needs to reject the promise with an error. 

That same seems to apply request() method's algorithm:

>  If the previous step threw an exception, <a>reject</a> |promise| with that exception. 

It think that needs to be an Error.

**Comment by jyasskin** [comment]
Users don't call the [permission request algorithm](https://w3c.github.io/permissions/#permission-request-algorithm) directly; it's only used by [`request()`](https://w3c.github.io/permissions/#dom-permissions-request), which correctly translates the exception into a project rejection. So, I think it's correct, but maybe should be made more clear somehow?

We generally reject promises with things like [`SecurityError`](https://heycam.github.io/webidl/#securityerror), which are `DOMException`s instead of `Error`s.

**Comment by marcoscaceres** [comment]
Right, sorry - still get my DOMExceptions vs Errors confused - re-read the WebIDL spec and it makes sense to DOMException there. I almost feel like we should label these operations as abstract. Closing.
