### ISSUE TITLE
Should 'prompt' be renamed as 'default'?

### ISSUE THREAD

**Issue by mounirlamouri** [w3c/permissions#12]
The TAG review points that 'prompt' wasn't generic enough and should be renamed as 'default' or maybe introduce a new state.

**Comment by mounirlamouri** [comment]
_prompt_ is one of the main reason why ```query()``` exists. We have strong reasons to think that developers want to know whether a call will prompt. Naming that state _default_ will simply leave the confusion.

The example given in the TAG review that says that a browser might decide in its own judgement whether a permissino is granted would be simple to expose using ```query()```. Basically, the browser would expose whether a call at that moment would succeed.

Given that this is an enum, we can easily have a new entry added later. For example _unknown_. However, I would prefer to avoid adding it unless we have real life use case. As of today, I have not heard of any convincing one.

**Comment by KenjiBaheux** [comment]
I can see a use case for "unknown".

For Background Sync, we are exploring a permission model where the user agent would process BG sync requests (esp. one-offs) without asking the user. However, if the user agent determines that the combination of a given network and website may lead to privacy concerns, it would then prompt the user.

In this model, the user agent wouldn't be able to answer query() ahead of time and would return "unknown".

**Comment by mounirlamouri** [comment]
I presume that if the user agent is able to make a decision when the API call is being made, it can tell whether at that time it would allow the call to go trough, right? If your algorithm depends on some parameters like origin, previous usage, type of network, there are no reasons why ```.query()``` shouldn't work.

It might be more complicated for algorithms depending on very unstable data. To take an extreme example: if the permission granting is randomly set based on the time of day. Calling ```.query()``` at a time ```t``` will unlikely help you knowing whether you will have the permission granted at time ```t'```. Obviously, that's always true, but not for very close ```t``` and ```t'```.

Another example where the current model would be tricky to apply is for quantic permissions: if observing the permission could modify it.

**Comment by mounirlamouri** [comment]
CC @slightlyoff @marcoscaceres

I'm closing that issue. Feel free to reopen if you disagree.

**Comment by KenjiBaheux** [comment]
> If your algorithm depends on some parameters like origin, previous usage, type of network, there are no reasons why .query() shouldn't work.

The issue is that when you register for a bg sync, we don't know what these parameters will be when the bg sync opportunity arise.

Suppose that a user is using a web app, called Miracle Deluxe, on a flaky connection. One of his action failed because of network issues. The web app would then register for a one-off bg sync opportunity [1].

[2] A couple of hours later, the user arrives at his work place and his device connects to the office's WiFi. The user might not want to let his employer knows that he's using Miracle Deluxe. In the permission model being explored, the user agent would notice that the user never accessed Miracle Deluxe on this particular network. The user agent would prompt in that case. 

[3] The user comes back home and his device connects to his home WiFi. The user agent would notice that the user has accessed Miracle Deluxe on this network and decide to grant a no prompt one-off bg sync.

[4] Same scenario but with a non sensitive web app, called Everyday Happenings. Let's assume that the user has told his user agent to always allow bg sync for Everyday Happenings.

Query at [1]: "unknown"
Query at [2]: "prompt"
Query at [3]: "granted"
Query by Everyday Happenings: "granted"
