### ISSUE TITLE
Handle non-fully-active documents

### ISSUE THREAD

**Issue by jan-ivar** [w3c/permissions#162]
It's possible to invoke methods on objects in windows with no longer fully-active documents, because DOM. Generally, these are edge-cases with few if any use-cases other than exploits.

While individual specs are required to think about such cases, very [few do](https://fullscreen.spec.whatwg.org/#dom-element-requestfullscreen).

This presents a unique problem for APIs exposing powerful features behind permissions, because we tie permissions to realms and origins. Specifically, we have to be careful about things like showing the right requesting origin in permission prompts, something that's only guaranteed to make sense from documents that are still [fully active](https://html.spec.whatwg.org/multipage/browsers.html#fully-active).

As an extra safeguard, would it make sense to add prose to the [request permission to use](https://w3c.github.io/permissions/#request-permission-to-use) algorithm to return `"denied"` if the responsible document is no longer *fully active*?

This would expressly forbid powerful features in these edge cases. I can't think of a case where doing so would be a problem.

@jyasskin Thoughts?

**Comment by jan-ivar** [comment]
From a practical standpoint, this would give implementers an error to throw (e.g. `"NotAllowedError"` in gUM) in specs that haven't expressly thought about this.

**Comment by jyasskin** [comment]
I think the spec currently permits browsers to set the [permission state](https://w3c.github.io/permissions/#permission-state) to "denied" when a document isn't [fully-active](https://html.spec.whatwg.org/multipage/browsers.html#fully-active), on the theory that becoming not-fully-active is new information about the user's intent, and that has the effect of making [request permission](https://w3c.github.io/permissions/#request-permission-to-use) also return "denied".

It sounds like a good idea to require this instead of just allowing it. @raymeskhoury, what do you think?

**Comment by raymeskhoury** [comment]
sgtm. We might want to put this inside the section on retrieving the permission state though.

**Comment by rakina** [comment]
This thread is talking about "fully active" state changing due to the document getting detached. For that case, not allowing to query permissions seems reasonable. There's another way for the "fully active" state to change: the user navigated away and the page gets into the back/forward cache (see [article](https://web.dev/bfcache/), [guide](https://github.com/w3ctag/design-principles/pull/317)). When that happens, the page can't run script so querying permissions is not possible and should not be a problem.

However, there's also the "permission status change" event which I think this thread hasn't talked about, but is being updated in @marcoscaceres' PR: https://github.com/w3c/permissions/pull/249 . I'm not really sure when this will be triggered - is it possible for this to be triggered by another frame/page? If so we need to decide whether we should "drop" these changes (never send the "change" event, so when the document becomes fully active again it needs to proactively query the current state of things), or update the frame/page with the latest state when it becomes fully active again if any change has happened while it's not fully active (Note that this should update the document with the "latest status" instead of a full queue of events. See last paragraph of [2.8.2](https://pr-preview.s3.amazonaws.com/w3ctag/design-principles/317/b295eb7...rakina:79aa652.html#listen-fully-active) for more details)

**Comment by marcoscaceres** [comment]
Sorry for the delay, @rakina. I've been trying to educate myself further about BFCache. 

> However, there's also the "permission status change" event which I think this thread hasn't talked about, but is being updated in @marcoscaceres' PR: #249 . I'm not really sure when this will be triggered - is it possible for this to be triggered by another frame/page?

It cannot be updated by another page in the context of this specification. However, the end-user could revoke a permission manually by manually changing a site's permissions' settings.

There are two cases I can think of (there may be others, and hopefully other folks will chime in!):

## Case 1 - BF restore 

 1. Parent document creates an iframe (page1.html). 
 2. permission is granted for powerful feature X.
 3. iframe is navigated to another page (page2.html) - page1.html is now in BFCache.
 4. User revokes permission for origin for power feature X.
 5. `navigator.history.back();` gets called. 
 6. page1.html's document gets unfrozen from BFCache. 

Now we have a situation: 
 1. Should the permission change event be delivered? (probably yes - this might already happen automatically, but it's hard to test as BFCache is somewhat unreliable). 
 2. Every API MUST recheck if it's "allowed to" use the API, like Geolocation now does (we make that clear in the TAG Recommendation). 

## Case 2 - Reference Theft

 1. Parent document creates an iframe (page1.html). 
 2. permission is granted for powerful feature X.
 3. Parent *steals a pointer* to the iframe's permission instance, causing GC to no longer be possible for that instance: that is, `const stolen = iframe.contentWindow.navigator.permissions; // lulz`
 4. iframe is navigated to another page (page2.html).
 5. `navigator.history.back();` gets called - new window/document gets created.
 6. Parent frame calls `stolen.query({name: "geolocation"})`.
 
In this case - which has no practical application whatsoever: 
 - Return a promise rejected with "NotAllowed" `DOMException`.

**Comment by marcoscaceres** [comment]
@rakina wrote: 
>  If so we need to decide whether we should "drop" these changes (never send the "change" event, so when the document becomes fully active again it needs to proactively query the current state of things), 

[In case 1 above](https://github.com/w3c/permissions/issues/162#issuecomment-883020373), I suggested that maybe the browser should wait and deliver the changes... but now I thinking it's not worth it (given complexity), and we should do as you eluded to: let the developer recheck the permission state themselves on `"pageshow"`. 

That keeps things simple and provides all the necessary assurances that everything is up to date with respect to any permission.

**Comment by marcoscaceres** [comment]
As the API only deals with querying permissions, I've updated the title of this issue to restrict the scope. 

With respect to "granting permission to non-fully-active documents", that needs to be handled by the spec of each powerful feature. @rakina I'm not sure if there is wording around that in [the guide](https://github.com/w3ctag/design-principles/pull/317), but something to consider.

**Comment by jyasskin** [comment]
@marcoscaceres This specification defines how permissions are handled in general, rather than just an API, so it's plausible for it to take a stance on whether non-fully-active documents can have permission to do anything.

**Comment by marcoscaceres** [comment]
@jyasskin, @rakina, yes, you are right. In [reading the current permission state](https://w3c.github.io/permissions/#reading-current-states), we can check if the |document| is "fully active" (and reject at that point?).

Concretely in JS below.

 * Chrome: resolves the promise with `undefined`. 
 * Firefox: never resolves. 
 
```JS
async function test() {
  const iframe = await loadIframe();
  // Prevent GC from collecting the permissions object.
  const permissions = iframe.contentWindow.navigator.permissions;

  // Make iframe no longer fully active
  iframe.remove();

  // Deny or throw?
  const perm = await permissions.query({
    name: "geolocation",
  });

  console.assert(
    perm.state === "denied",
    "Expected permission state to be 'denied'"
  );
}

async function loadIframe() {
  const iframe = document.createElement("iframe");
  iframe.src = "/";
  document.body.appendChild(iframe);
  await new Promise((resolve) => {
    iframe.onload = resolve;
  });
  return iframe;
}

test();
```

**Comment by rakina** [comment]
Thanks @marcoscaceres! Sorry for the delay from my side, I was out for a bit.
I think I'm still a bit concerned if sites will break if we don't send the `onchange` event for the `PermissionState`, so let me try to understand how it's used. Are sites expected to call `permissions.query()` every time they want to use an API that needs permissions, or is it more common for them to query only once and listen to the `onchange` event to update the state?

If it's the latter, I'm worried that sites might lose out on changes (especially to when they lose permission). What would happen if the page tries to use an API without permission? Will it just throw error/never return/etc? Can that potentially be dangerous? I wonder if it might cause sites to just inexplicably break because the permission-granted-path is used instead of no-permission-path, since the site won't be aware of the change.

**Comment by rakina** [comment]
> Every API MUST recheck if it's "allowed to" use the powerful feature, like Geolocation now does (we make that clear in the TAG recommendation, if it's not already clear).

I think it makes sense to add this recommendation regardless of our decision to send updated events or not, as some APIs like Geolocation that you mentioned already don't guarantee that updates that happen while bfcached are sent. I'll re-read my TAG doc and see if I need to emphasize this more, thanks!

> In reading the current permission state, we can check if the |document| is "fully active" (and reject at that point?).

I think I'm fine with rejecting if that fits the API design. I think this a problem only for iframe detach - it's not a problem for bfcache since you can't access the page while bfcached, and can't have other page refer to the page before (per https://github.com/whatwg/html/issues/6858)

**Comment by marcoscaceres** [comment]
Hi @rakina, sorry for throwing you into the deep end of this API! Thanks for sticking with it! 

> I think I'm still a bit concerned if sites will break if we don't send the onchange event for the `PermissionState`, so let me try to understand how it's used. Are sites expected to call `permissions.query()` every time they want to use an API that needs permissions, or is it more common for them to query only once and listen to the onchange event to update the state?

As you suggest, they would call it once, hold the reference to say `"const perm = permissions.query(...)"`, and use rely on the events. 

> If it's the latter, I'm worried that sites might lose out on changes (especially to when they lose permission). 

Ok, so, potentially... let's work through this use case together:

 1. Page loads.
 2. Developer creates a permission object (`perm`) and registers "change" listeners.
 3. Window navigates, page gets BFCached. 
 4. In the new page, `N` permissions change ... some time passes ... back button pressed!
 5. Page comes back to life. 

So, "N Permissions" changed. For example, Geolocation was enabled, then disabled, then enabled again, etc. Other permissions changed too. 

Personally, I don't think it would make sense to queue up a bunch of events (or even the last event) at that point, as it would be confusing to deliver them. An extreme case, it would have multiple change events.  

I think the best thing to do is listen for "pageshow", and check if `event.persisted`. Then call `permissions.query()` again and check if the permissions have changed, and rewire the events.

> What would happen if the page tries to use an API without permission? Will it just throw error/never return/etc? 

Most APIs would throw/reject, which is ok IMO. But they need to do code defensively, because permissions could potentially change without notification. 

> Can that potentially be dangerous? I wonder if it might cause sites to just inexplicably break because the permission-granted-path is used instead of no-permission-path, since the site won't be aware of the change.

I don't think so (but *maybe*!). But if the code has been written defensively - which they would need to do regardless, because they might not be allowed to use the API by policy - then it should be ok. 

> I think I'm fine with rejecting if that fits the API design. I think this a problem only for iframe detach - it's not a problem for bfcache since you can't access the page while bfcached, and can't have other page refer to the page before (per whatwg/html#6858)

Exactly, yes. This may need some spec changes, but it's manageable.

**Comment by fergald** [comment]
I agree that it doesn't make sense to deliver all of the events that happened while in BFCache because but we either have to spec one of
1. these events are not reliable and you must always write a pageshow handler if you want ensure that your JS state matches the true state
2. we will deliver events based on what happened when you were in BFCache
  a. the event will come after pageshow
  b. the event sill come before pageshow

I think 1. seems very bad for developer ergonomics and you can't really say "this only happens with bfcache" because bfcache happens a lot.

I prefer 2. because for pages without a pageshow handler, it just works and even for many pages with a pageshow handler it just works. The exception is a pageshow handler that cares about permissions state but these are broken right now and also seem like they would be very rare anyway.

BTW, I think a similar comment applies to geolocation updates too.

**Comment by rakina** [comment]
@marcoscaceres, what do you think about @fergald's suggestion to spec #2? Sorry to backtrack a bit, but I discussed this with Fergal a couple weeks ago and now lean towards making existing feature's spec to ensure pages would "just work" without having to deal with new BFCache expectations, both here and for the Geolocation API we updated a while back.

I think that aligns better with the [Priority of Constituencies](https://www.w3.org/TR/design-principles/#priority-of-constituencies) - if we leave the responsibility to the developer to proactively update their sites to handle bfcache, end users might end up suffering weird cases they might have no idea about on sites that has no idea about BFCache. Specifying ways to make existing usage of existing APIs to more or less seamlessly work with BFCache seems to be the right choice, as the burden should be on browsers to make sure things will work (either by expending effort to support the features, or disabling BFCache when that's not possible). It does complicate the spec a bit, but we'll be happy to help writing them if needed!

**Comment by marcoscaceres** [comment]
I'm in agreement that it should "just work". However, it now becomes a matter of implementation commitments depending on how much additional infrastructure is needed to coalesce the permissions changes (hi @jan-ivar, @johannhof on the Gecko side!). 

> It does complicate the spec a bit, but we'll be happy to help writing them if needed!

That would be amazing! Continued help with https://github.com/w3c/permissions/pull/249 would be greatly appreciated. 

Maybe we can do that in two parts?... the easy part might be landing what I've already spec'ed in #249, with the bonus is that I've got a patch approved and ready to land for Gecko. I would need you or other folks from the Chrome side to approve #249 and commit to implementing that. 

Then, in parallel, we can tackle the the part needed to deal with queuing the events and make it work seamlessly as per @fergald's suggestion 2.

**Comment by rakina** [comment]
Thanks, I think merging #249 and working on the other suggestion separately should work. I think the implementation changes won't be too big in Chrome (just need to track if we've sent a change event before somehow), and if the Permissions people in Chrome can't work on it, I think the BFCache people can commit to implementing it later on. I've filed https://bugs.chromium.org/p/chromium/issues/detail?id=1238709 for both the changes!
