### ISSUE TITLE
Clipboard permissions

### ISSUE THREAD

**Issue by martinthomson** [w3c/permissions#175]
The current clipboard API spec claims that there are two permissions: "clipboard-read" and "clipboard-write".  The current spec includes just one permission: "clipboard".  Which is it?

**Comment by jyasskin** [comment]
@garykac, could you send a PR to make these consistent?

**Comment by dway123** [comment]
I've sent up a PR. As per the Clipboard API spec, there should be 2 separate permissions: "clipboard-read" and "clipboard-write".

**Comment by marcoscaceres** [comment]
As I mentioned in https://github.com/w3c/permissions/pull/209#issuecomment-637899018, I was expecting something like the following, to match other things in the permission spec:

```
enum ClipboardMode { "read", "write" };
dictionary ClipboardPermissionDescriptor : PermissionDescriptor {
   ClipboardMode mode = "read";
};
```

The permission name should remain "clipboard", no?

**Comment by dway123** [comment]
In the Clipboard Specification, it mentions that:

> two separate permissions are defined: "clipboard-read" and "clipboard-write"

From there, these 2 permissions each are further enhanced by a ClipboardPermissionDescriptor, which provides an allowWithoutGesture parameter.

I was thinking it would therefore make sense to have these 2 separate permissions here, with a reference to the Clipboard spec, so that the permission descriptor is defined in the clipboard spec, and doesn't need to be synced between 2 specifications.

Chrome also happens to have implemented these two separate permissions already, and the MDN also documents using these separate permissions.

Changing the Clipboard specification/implementation to have one unified clipboard permission does seem to be more consistent with the existing Permissions spec, but this could break sites already expecting there to be two separate permissions.

**Comment by dway123** [comment]
Would it make sense to add these "clipboard-read" and "clipboard-write" permissions, given my previous message?

**Comment by marcoscaceres** [comment]
Sorry for the delay... I don't think this "-read" and "-write" sets a great precedence. However, I'm sympathetic that Chrome shipped and sites may break.

**Comment by dway123** [comment]
Yeah sorry, I do agree that a single Clipboard permission with the enum you've mentioned would be more consistent with other permissions, and preferable if this were not already reviewed and shipped so long ago.

Thank you for the review and approval. I think this issue can considered resolved and closed now.

**Comment by marcoscaceres** [comment]
> preferable if this were not already reviewed and shipped so long ago.

I haven't followed Clipboard closely, but do you know if folks from Gecko and WebKit are contributing to the Clipboard discussion over in the other repo? Is this permission set also shipping in other browser?

**Comment by dway123** [comment]
I did a bit more digging...

It seems this Clipboard permission discussion started with an [issue](https://github.com/w3c/clipboard-apis/issues/51) and [TAG review](https://github.com/w3ctag/design-reviews/issues/222) with folks from Gecko + Blink + Edge participating, which resulted in this [spec change](https://github.com/w3c/clipboard-apis/commit/aa1f8ac45ffc3ff9035fa64519c5c822ab28469c).

Since then, there was recent activity [here](https://github.com/w3c/clipboard-apis/issues/101), where there doesn't seem to be [cross-browser support](https://github.com/w3c/clipboard-apis/issues/101#issuecomment-586830010).

**Comment by marcoscaceres** [comment]
Thanks for digging @dway123, I'll see if I can find the module owner or person responsible on the Gecko side.

**Comment by saschanaz** [comment]
>but do you know if folks from Gecko and WebKit are contributing to the Clipboard discussion over in the other repo?

I guess this was the WebKit's position back in February. https://github.com/w3c/clipboard-apis/issues/101#issuecomment-588089651

>FWIW, Safari will likely never support non-gesture based copy & paste permission (as in we'd likely always require a new gesture for each copy & paste). As such, we don't see this permission ever being implemented / supported in Safari.

**Comment by marcoscaceres** [comment]
@annevk is telling me we are not going to support `-read` either in Gecko either. We should probably revise the spec.

**Comment by dway123** [comment]
Thank you for finding a responsible module owner and providing their feedback. I understand that Gecko and Webkit may not be interested in this `-read` / `-write` permission naming now.

That said, this did already make it into Blink, so it's not possible for us to unship or change this permission name without breaking many sites/users. It's unfortunate this wasn't caught or addressed earlier during the TAG review/issues.

**Comment by othermaciej** [comment]
It seems like the right thing to do is remove `-read` from the spec, since it is not likely to obtain sufficient implementation experience via multiple implementations. Chrome/Blink can keep it as a nonstandard feature or even document it elsewhere.

**Comment by marcoscaceres** [comment]
Sent PR to remove "-read" https://github.com/w3c/permissions/pull/222

**Comment by marcoscaceres** [comment]
Could someone who is working on Clipboard do the same over on https://github.com/w3c/clipboard-apis ? @saschanaz maybe?

**Comment by saschanaz** [comment]
I'm not exactly working on it, maybe @garykac? I can try if everyone is in Summer break 😁

**Comment by rniwa** [comment]
Shouldn't we also remove "clipboard-write" given we wouldn't have multiple implementation support for that either??
