### ISSUE TITLE
Publish new WD to /TR?

### ISSUE THREAD

**Issue by wseltzer** [w3c/permissions#215]
I see updates in the Editors' Draft, but the last /TR publication was in 2017. Anything W3C team can hep with, such as getting updates auto-published?

**Comment by marcoscaceres** [comment]
It should be all fine from the W3C side... I think the deploy.sh script is stuck. I'm wondering if we @jyasskin has a few spare cycles to debug it? It's probably something silly that's broke it.

**Comment by marcoscaceres** [comment]
@wseltzer maybe you or someone on the W3C side can check how other BikeShed specs end up on /TR/? I've very little knowledge of BikeShed unfortunately.

**Comment by wseltzer** [comment]
Thanks @marcoscaceres I'll look around, and perhaps @plehegar can help.

**Comment by jyasskin** [comment]
If I remember correctly, I tried to set up Echidna, ran into a group of bugs, reported at least some of them, and then didn't get back to finishing it when folks replied to the bug reports. I'll take a look on Monday, and bug folks via IRC in real-time if things don't work.

**Comment by jyasskin** [comment]
Notes as I'm investigating today:

* https://labs.w3.org/echidna/api/status?id=1c133e60-98c4-40d8-88c4-f70afcfd8af6 has the Echidna error from the last run in June. 
* That indicates that the problem with the current `.travisci.yml` is diagnosed in https://github.com/w3c/echidna/issues/491.
* https://github.com/w3c/echidna/issues/487 indicates that I had already tried the fix proposed in 491 without success, but that bug is supposedly fixed now, so I'll try again.
* https://github.com/tabatkins/bikeshed/issues/1102#issuecomment-332021534 makes it difficult to use `bikeshed echidna` safely since Bikeshed wants to send a TAR to Echidna, but Echidna only accepts a TAR with a human's username and password, not with the safer per-spec token.

**Comment by jyasskin** [comment]
96646df435fa291bf4ad320c10b96a0fbb9673af let me use `bikeshed echidna` locally, so https://www.w3.org/TR/permissions/ is up to date as of today. However, that immediately changed the "latest" version, so https://lists.w3.org/Archives/Public/public-tr-notifications/2020Jul/0055.html fails the "latest-is-not-previous" check again. I don't see how this can ever work...

**Comment by marcoscaceres** [comment]
@tabatkins was looking to fix that, so it would pull the previous publish date from the biblio.

**Comment by tabatkins** [comment]
I already did fix that, check the issue thread you brought it up in ^_^

**Comment by tabatkins** [comment]
Or, for Jeffrey, check <https://tabatkins.github.io/bikeshed/#metadata-previous-version> ^_^

**Comment by marcoscaceres** [comment]
Awesome! thanks @tabatkins!

**Comment by jyasskin** [comment]
@tabatkins Thanks! I could use that linked from the echidna instructions ... maybe in https://tabatkins.github.io/bikeshed/#cli-echidna? It's also broken for this particular spec: https://github.com/tabatkins/bikeshed/issues/1737 🤪

**Comment by plehegar** [comment]
The draft was published. should this be closed?

**Comment by wseltzer** [comment]
Thanks, closing
