### ISSUE TITLE
PWA install permission

### ISSUE THREAD

**Issue by FluorescentHallucinogen** [w3c/permissions#227]
Since consensus on `beforeinstallprompt` and `prompt()` [was not reached](https://github.com/mozilla/standards-positions/issues/84), what about asking users to install web app as any other permission and moving install prompt into Web Permissions API? Something like:

```js
navigator.permissions.query({ name: "install" })
```

Think of it as web app asks for permission to install itself on the device.

This idea perfectly fits with [Web Install API](https://github.com/PEConn/web-install-explainer/), where one website would allow to request the installation of another website. Website should first ask permission for that. If website can ask permission to install another website, what about asking permission to install itself?

This idea perfectly fits with various browser heuristics applicable to other permissions like "Websites that ask users permission when they first arrive without any context often have very low permission accept rates; website with low permission accept rates can't ask this permission" (see [Quieter permission UI for notifications](https://blog.chromium.org/2020/01/introducing-quieter-permission-ui-for.html)), "Users who repeatedly deny e.g. geolocation permissions across websites will be not asked geolocation permissions", etc. These heuristics and other permission policies applicable to install permission too.

@b1tr0t @mgiuca @PEConn @marcoscaceres Thought?

**Comment by mgiuca** [comment]
Would such an API have any functional difference to BeforeInstallPrompt? It would have essentially the same UX, and be gated behind engagement or something similar.

The objections raised by opponents of BeforeInstallPrompt (from Mozilla and Apple) on w3c/manifest#835 were not about the nature of the interface per se, but the user experience. From their perspective, I don't see how this changes the equation. And those are the people you have to convince to create a standard.

From Chromium's perspective (i.e. mine), I don't think we'd object to this proposal from a user experience perspective, but since it's functionally equivalent to an API we already offer that's in widespread use, I don't think there would be a lot of appetite to change over to an incompatible but equivalent API, and ask all the developers to rewrite their install prompting code.

**Comment by rniwa** [comment]
As I stated in https://github.com/w3c/manifest/issues/835, we don't think letting a website trigger any prompt to "install" web app is desirable. As such, this proposal as the same issue as `beforeinstallprompt`.

**Comment by marcoscaceres** [comment]
Putting aside BIP, although the idea in principle is sensible, it doesn't map well to the Permissions API, which is about controlling permissions of so called "powerful features". I think if we were going to have an Install API, it would have to be its own thing.
