### ISSUE TITLE
Why "prompt" instead of "default"?

### ISSUE THREAD

**Issue by annevk** [w3c/permissions#25]
Do we really need to make this enum different from https://notifications.spec.whatwg.org/? It would be nice to consolidate.

**Comment by mounirlamouri** [comment]
One of the main reasons why we have this API is to know whether a call will prompt the user, thus breaking the application flow. ```default``` really means ```other``` and here, we explicitely mean that the call wil prompt so we prefered to be explicit.

**Comment by annevk** [comment]
Euhm, what call? E.g. the Notifications API requires asking for `default`. Fullscreen works, but the user is asked to confirm. `default` seems much clearer for both. `prompt` might make sense for geolocation but is not generally useful and `default` works just as well for geolocation.

**Comment by annevk** [comment]
What `default` means in the context of permissions by the way, is `denied`, but there's still an option of sorts to convince the user otherwise. That is why `prompt` is so weird. `showNotification()` would not prompt, but would fail.

**Comment by sicking** [comment]
I personally prefer `prompt` over `default`. `default` is arguably somewhat ambiguous if a UA decide to deny by default. For example for a UA which deny some permission for all http connections by default. Should such a UA return `deny` or `default`?

But I also agree with @mounirlamouri that one of the main use cases for this API is to enable a website to know if a given function call will put up a prompt or not. So it's preferable if the API answers that question as clearly as possible.

**Comment by travisleithead** [comment]
Bikeshedding: I like 'ask' instead of 'default' or 'prompt'. 'Ask' is more generic and doesn't imply any form of UI, it just means "denied, but hang on a minute, I'll go check..."

**Comment by sicking** [comment]
I don't have an opinion regarding `ask` vs. `prompt`. Both are equally fine with me.

**Comment by marcoscaceres** [comment]
Ask seems nice.

**Comment by annevk** [comment]
@sicking that is clearly spelled out, you would use "denied". "default" means you can ask, but currently don't have permission.

And again, what given function call will prompt? That is not at all clear and I've given some examples to that effect. You're only relaying the permission here.

**Comment by sicking** [comment]
> @sicking that is clearly spelled out, you would use "denied". "default" means you can ask, but currently don't have permission.

So then `default` doesn't even mean "default behavior of the UA"? But rather "UA will show a prompt to the user"?

> And again, what given function call will prompt? That is not at all clear and I've given some examples to that effect. You're only relaying the permission here.

Would this be more clear if we used `default` rather than `prompt`/`ask`? I.e. is this related to this issue or an argument against this API as a whole?

**Comment by annevk** [comment]
"default" means deny if the feature is used without some out-of-band action, like prompting the user. The terminology was discussed when we introduced the Notifications API. I'm not sure why we want to revisit it now. Seems bad to rename things every other year.

**Comment by martinthomson** [comment]
I think that `default` is a mistake.  Our policies with respect to default might evolve over time, but the semantics need to remain constant.  `ask` or `prompt` have meanings that match the semantics.

**Comment by annevk** [comment]
No they don't. If I implemented `showNotification`/`new Notification()` and used the permissions API underneath it would return `ask`/`prompt` but instead I would have to reject the promise/dispatch an error event. Makes no sense.

**Comment by sicking** [comment]
I would say that the `prompt` answer still better describes how `Notification.requestPermission()` behaves.

I agree though that it doesn't as well describe the behavior of the `showNotification()` function.

But I don't think it's obvious that using `default` would be a net win. I.e. we'd describe the behavior of `showNotification()` a *little* better. `denied` really would be a better answer for that. But we'd also describe the behavior of `Notification.requestPermission()` a worse, since `prompt` is a better description of that.

And for all other APIs that we have so far, `prompt` is more descriptive than `default`.

So all in all I think that `prompt` (or `ask`) is better than `default`. And we'd have to document the weirdness that `showNotification()`/`new Notification` rejects if permission hasn't been granted.

**Comment by annevk** [comment]
No. `Notification.requestPermission()` would be implemented in terms of a `Permission.request("notification")` or some such. That would not return `prompt` if the user did not take any action or clicked outside the dialog, it would return `default`.

**Comment by sicking** [comment]
What I'm saying is that in the initial state, `Notification.requestPermission()` (or whatever syntax we'll use for the equivalent functionality) prompts the user. Hence returning `prompt` for `navigator.permissions.query({name:'notifications'})` seems like a good descriptive answer of how the `Notification.requestPermission()` (or whatever syntax we'll use for the equivalent functionality) behaves in its default state.

Likewise when `navigator.permissions.query({name:'notifications'})` returns `granted`, `Notification.requestPermission()` (or whatever) would return `granted` without prompting the user. And when `navigator.permissions.query({name:'notifications'})` returns `denied`, `Notification.requestPermission()` would return `denied` without prompting the user.

In short, returning `prompt` seems like a better description than `default` for `navigator.permissions.query({name:'notifications'})` when it comes to how the `Navigator.requestPermission()` part of the notification API behaves.


I do agree that `navigator.permissions.query({name:'notifications'})` returning `prompt` is a less good description of how the `showNotification()` part of the notification API behaves, since in that state `showNotification()` would fail rather than prompt the user.

But as mentioned above, I don't think that returning `default` is a particularly good description either, since the behavior is actually more like `denied`. So either way it seems like we'll need to make it clear to developers through documentation how `showNotification()` behaves for the various return values from `navigator.permissions.query({name:'notifications'})`.

So all in all it seems like more gain and less loss to use `prompt` (or `ask`) rather than `default`.

**Comment by annevk** [comment]
You would not implement `Notification.requestPermission()` in terms of `query()`. That doesn't work.

**Comment by martinthomson** [comment]
@annevk, maybe it's obvious to you, but can you explain why?

I model query as something like "if you asked for this, what would happen?" In the case of notifications, I can see the complication that arises (does that apply to `requestPermission` or `showNotification`). But I think that we just have to choose one or other.

Since `requestPermission` results in better actionable information, pick that.

**Comment by annevk** [comment]
@martinthomson because `query()` does not prompt. The underlying feature of `Notification.requestPermission()` is not `query()`, it's `request()`. And `request()` would not return "prompt", it would simply prompt.

**Comment by mounirlamouri** [comment]
@annevk discussed this issue offline and agreed to keep ```prompt```.

**Comment by martinthomson** [comment]
Quite timely that you choose to close this now just when I'm ready to talk about things that don't prompt. :)
