### ISSUE TITLE
Definition of PermissionStatus lifetime

### ISSUE THREAD

**Issue by szewai** [w3c/permissions#266]
According to current spec (https://w3c.github.io/permissions/#permissionstatus-gc), PermissionStatus object should be kept alive if it has event listener or a task is queued. This definition may prolong the lifetime of PermissionStatus object (once client sets change event listener, the object will never be collected). 

For example, in the case where we create a PermissionStatus with an iframe and then remove the iframe:
```
iframe.contentWindow.navigator.permissions.query({name:featureName}).then((status) => {
    status.onchange = stateChangeCallback;
    iframe.contentWindow.asyncRequestPermissionForFeature(featureName); 
    setTimeout(() => { iframe.remove(); }, someTimeout);
    status = null;
}
```
Is it necessary to keep status object alive and fire events after iframe is gone?
It seems current Chrome currently stops firing events after global object is gone.

Spec should be more specific about when it's Okay to stop firing event (and stop keeping the PermissionStatus alive). "Only when PermissionStatus has no event listener" does not sound right.

**Comment by rniwa** [comment]
So to clarify, given that the specification doesn't say when UA may stop updating the permission status of a given realm, the behaviors of Chrome and Gecko are both spec compliant. What is rather confusing is the spec text written in [section 7.1. garbage collection](https://w3c.github.io/permissions/#permissionstatus-gc).

> While an PermissionStatus object has one or more event listeners registered for "change", there must be a strong reference from the Window or WorkerGlobalScope object that the PermissionStatus object’s constructor was invoked from to the PermissionStatus object itself.
>
> While there is a task queued by an PermissionStatus object on the permissions task source, there must be a strong reference from the Window or WorkerGlobalScope object that the PermissionStatus object’s constructor was invoked from to that PermissionStatus object.

Both of these points are tautological / redundant since if a given realm's permissions were to change, then UA must schedule a task to dispatch `change` event [per section 7](https://w3c.github.io/permissions/#permissionstatus-interface). ECMA semantics of exotic objects is such that object can't spontaneously disappear and come back into existence. So, as long as there are possibilities that an event can be fired on `PermissionStatus` interface in the future, UA must keep this JS object alive.

More specifically, in implementations such as Blink and WebKit where the exotic object consist of the underlying C++ object as well as JS wrapper objects in V8 & JSC, it would mean that such a JS wrapper object must be kept alive so long as there is a possibility that a `change` event can fired on `PermissionStatus` object such that the event is anyway observable by the author scripts.

I think a better way to communicate this intent is to specify that the permission status of a realm MUST not change when the global object is a [Window](https://html.spec.whatwg.org/multipage/window-object.html#the-window-object) and its [browsing context](https://html.spec.whatwg.org/multipage/browsers.html#browsing-context) is null.

**Comment by marcoscaceres** [comment]
Agree, let's see we can phrase what's in the spec better. cc'ing @smaug----, for input on the Gecko side.

**Comment by smaug----** [comment]
(In Gecko JS wrapper doesn't need to be kept alive. It can be recreated when needed.)

"permission status of a realm MUST not change when the global object is a Window and its browsing context is null."
did you mean 'its browsing context is non-null'?

**Comment by marcoscaceres** [comment]
In #360, we are simplifying it to just: 

> A {{PermissionStatus}} object MUST NOT be garbage collected if it has an [=event listener=] whose type is `change`.

That capture the intent that this works:

```JS
(async () => {
  const perm = await navigator.permissions.query({ name: "geolocation" });
  perm.onchange = console.log;
  // bye bye perm... but not garbage collected
})();
```
