### ISSUE TITLE
Flesh out more complex permission issues we see down the road

### ISSUE THREAD

**Issue by progers** [w3c/permissions#28]
I don't think the fullscreen issues have been fleshed out in this api (we have similar issues with push notifications). The problem is mixed permissions: the current fullscreen and pointer lock permissions are disconnected and the proposals for unifying them don't (afaik) involve this api.

**Comment by mounirlamouri** [comment]
Fullscreen seems like a quite simple API in the context of permissions as far as I can tell.

Pointer lock is more interesting because it requires fullscreen. So does Screen Orientation in some contexts. Some APIs also require user interaction. Like fullscreen, actually ;)

I think what makes these permissions interesting is that the API call could fail because the API is expecting some states. Even if an application is allowed to use the pointer lock API, it will always fail unless it is currently fullscreen.

My idea was to introduce a PermissionDetails (or PermissionInformation...) that would expose some information about the permissions. Pointerlock could be something like:
```js
{
  requiresFullscreen: true,
  requiresUserInteraction: false,
}
```

**Comment by marcoscaceres** [comment]
Closing, as the API has `PermissionDescriptor`.
