### ISSUE TITLE
Define underlying infrastructure

### ISSUE THREAD

**Issue by annevk** [w3c/permissions#33]
See e.g. Notifications API Standard or Storage Standard.

Specifications will need access to the underlying algorithms as to what the status of a permission is. They might also want to subscribe to change notifications as this might impact existing objects (e.g. for notifications we'd likely remove the notifications).

**Comment by jyasskin** [comment]
Are the [permission request algorithm](https://w3c.github.io/permissions/#permission-request-algorithm) and [permission revocation algorithm](https://w3c.github.io/permissions/#permission-revocation-algorithm) sufficient for the "change notifications", or do you want something more tailored?

Note that the revocation algorithm needs to pass the descriptor down and let the permission itself decide how to update storage. Assume I've done that when answering. :smiley:

**Comment by annevk** [comment]
I think one big problem is that origins are not accounted for. E.g., https://w3c.github.io/permissions/#dom-permissions-query does not state where it gets its origin value.

I think https://w3c.github.io/permissions/#boolean-permission-query-algorithm also needs to take an origin.

How do I store a permission for an origin?

(And note that for notifications I need to be able to do some of this synchronously. Although I suppose I could simply say "wait" or "pause" and reference HTML.)

**Comment by jyasskin** [comment]
#91 should let you do all of this synchronously using exported dfns, and has examples for the wording you'd use.

The origins come somewhat implicitly from [get a permission storage identifier](https://rawgit.com/jyasskin/permissions/update-permission/index.html#get-a-permission-storage-identifier), and we might have to change that up again due to https://noncombatant.github.io/permission-delegation-api/. I'm definitely happy to take suggestions on how to make it all clearer. My best guess at the moment is to find a better name for "permission storage identifier", but I don't have a concrete name in mind.

**Comment by annevk** [comment]
I see. "key" would already be clearer I think. Since this is a rather traditional key-value store if I'm not mistaken.

**Comment by marcoscaceres** [comment]
Closed by https://github.com/w3c/permissions/pull/91
