### ISSUE TITLE
Tackle origin

### ISSUE THREAD

**Issue by annevk** [w3c/permissions#34]
Permissions are tied to an origin. According to this specification they are tied to a global object. That's simply not true.

**Comment by martinthomson** [comment]
If I wanted to be pedantic here, I would say that permissions are actually tied to whatever the user agent decides they are tied to.  Historically, that's been a bit of a mess (domain name only, domain name and scheme, maybe origin).

In practice, however, I agree, this should use origin.  If browsers want to transfer a grant to one origin as implicitly granting other origins (e.g., `https://example.com:443` to all HTTPS ports on that name), then that is their business.

**Comment by mounirlamouri** [comment]
Why wouldn't a browser be able to have permissions depending on various parameters? I would be fine in switching back to origin (it used to be origin) but ideas like crowd approval/denial, reputation or user behaviour are not only origin related. Though, they usually include origin.

**Comment by annevk** [comment]
It needs to be at least origin-bound, possibly wider, otherwise developers have no guarantee. Currently the specification suggests that in a different global on the same origin, e.g. in a worker, stuff breaks. That's stupid.

**Comment by martinthomson** [comment]
I don't think I understand what the various parameters @mounirlamouri is referring to might be.  If the parameters are visible and explicit (i.e., the values in `PermissionDescriptor`), then it's OK to have different answers.  I agree with @annevk that having opaque criteria is going to generate surprises.

**Comment by npdoty** [comment]
We've seen implementations that use pairs of origins to determine permissions; Chrome was using this for Geolocation, so that users who granted an iframe of Google Maps on one site wouldn't automatically grant it to Google Maps embedded on a different site.

That is, whether permissions are granted, or what level of prompting the UA decides is appropriate, may vary on more than just the origin.

Some other possible parameters: Was this initiated by a user action? Have several permissions recently been denied by the user? Has it been a long time since the user originally granted this permission?

**Comment by annevk** [comment]
Sure, you can scope by more than origin and whether that is allowed and what shape that can take needs to be defined, but we need at least origin.

**Comment by annevk** [comment]
That is, we want to give the guarantee that if `<iframe src=https://example.com/b>` can use something, `<iframe src=https://example.com/a>` can too, provided all other things are equal.

**Comment by mounirlamouri** [comment]
Marking as fixed. I made origin the key information when storing/retrieving permissions. Please file follow-up issues if there are still problems there.
