### ISSUE TITLE
What should "retrieve the permission state" do for context related permissions?

### ISSUE THREAD

**Issue by mounirlamouri** [w3c/permissions#9]
Fullscreen requires a user interaction. Pointer lock requires the page to be fullscreen. Screen Orientation might require the page to be fullscreen.

If we had to have a permission associated with those features, how should the "retrieve the permission state" algorithm behave? Given that getting the permission state is asynchronous, code checking the state and using the feature would not work.

This said, it sounds unlikely that features like fullscreen or pointer lock need to be associated with a permission. Their security model is working fine as is for now.

**Comment by mounirlamouri** [comment]
If we want to support that, ```query()``` could return a ```PermissionStatus``` that contains a ```PermissionDetails``` instance exposing the fact that a ```userInteraction``` is required.

**Comment by martinthomson** [comment]
Are there any cases where an engagement gesture AND permission is required?  There was a case where code was landed in Chrome that caused both to be required (i.e., the doorhanger was only shown in response to a click or keypress).

I believe that it makes sense to be able to learn about the status of full screen.  We've recently had a discussion about this and it seems that the conclusion was to retain the permissions, but default the state of the permission to off.  There is a similar discussion now ongoing with respect to having write access to the clipboard.

That seems to be sensible for a class of capabilities like this.  Provide the capability because it is harmless in the general case, but provide users with a way to revoke access, especially in cases where the capability is abused by a site.  In other words, "ask forgiveness, not permission".

**Comment by marcoscaceres** [comment]
> This said, it sounds unlikely that features like fullscreen or pointer lock need to be associated with a permission. Their security model is working fine as is for now.

Permissions Policy can disable the ability to use certain permission in nested browsing contexts. These respond as "denied" via `.query()`. 

I don't think there is anything actionable to do here, so closing.
